const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const config = require('./identityLockConfig');
const { generateIdentityConditionedSceneImage } = require('./identityConditionedGenerator');
const { enhanceImage } = require('./imageEnhancement');
const insightFace = require('./identityInsightFace');
const {
  resolveCharacterMemoryForScene,
  compareWithCharacterMemory,
  materializeImageSource,
  prepareIdentityPackage
} = require('./characterMemoryStore');

async function generateSceneImageWithIdentityLock({
  scene,
  prompt,
  characterMemory = null,
  draft = null,
  jobId = null,
  sceneId = null,
  localOutputPath = null,
  plan = null,
  identityInstruction = '',
  rawPrompt = false,
  logger = null,
  brandContext = {}
}) {
  const effectiveSceneId = sceneId || scene?.sceneId || 'scene';
  const tempRoot = path.resolve(__dirname, '..', 'storage', 'ai-videos', String(jobId || 'temp'), 'identity-temp');
  await fs.promises.mkdir(tempRoot, { recursive: true });

  // ── STEP 1: Resolve Character Sheet and extract identity BEFORE generation ──
  let resolvedMemory = characterMemory;
  if (!resolvedMemory && draft) {
    resolvedMemory = await resolveCharacterMemoryForScene({ draft, scene, jobId });
  }

  const identityPackage = resolvedMemory
    ? await prepareIdentityPackage(resolvedMemory, logger)
    : null;

  if (identityPackage && logger) {
    logger(`[IdentityLock] Identity prepared for ${identityPackage.characterId} via ${identityPackage.identityEngine}`);
    logger(`[IdentityLock] Character Sheet: ${identityPackage.referencePath}`);
    logger(`[IdentityLock] Identity token: ${identityPackage.tokenPath}`);
  }

  let workingPath = null;
  let lastGeneration = null;
  let similarity = identityPackage ? 0 : 1;
  let attempts = 0;
  let faceSwapApplied = false;
  let enhanced = false;
  let identityConditioned = false;

  // ── STEP 2–4: Identity-conditioned generation → validate (confirm only) ──
  for (let attempt = 1; attempt <= config.MAX_RETRIES; attempt += 1) {
    attempts = attempt;
    const seed = crypto.randomInt(1, 2147483647);

    if (logger) {
      logger(`[IdentityLock] Scene ${effectiveSceneId} identity-conditioned attempt ${attempt}/${config.MAX_RETRIES}`);
    }

    const genStartTime = Date.now();
    lastGeneration = await generateIdentityConditionedSceneImage({
      prompt,
      scene,
      identityPackage,
      plan,
      identityInstruction,
      rawPrompt,
      seed,
      logger,
      brandContext
    });
    const genDurationMs = Date.now() - genStartTime;

    identityConditioned = Boolean(lastGeneration.identityConditioned);

    if (logger && identityPackage) {
      logger(`[IdentityLock] Generation engine: ${lastGeneration.engine} | geminiUsed=${Boolean(lastGeneration.geminiUsed)} | identityConditioned=${identityConditioned}`);
    }

    if (identityPackage && lastGeneration.geminiUsed) {
      if (!config.ALLOW_GEMINI_FALLBACK_WITHOUT_IDENTITY) {
        throw new Error(
          'Character scene was generated by Gemini instead of ComfyUI. Identity conditioning did not run.'
        );
      } else if (logger) {
        logger('[IdentityLock] WARNING: Generated scene via Gemini fallback (ComfyUI offline).');
      }
    }
    if (identityPackage && !lastGeneration.identityConditioned) {
      if (!config.ALLOW_GEMINI_FALLBACK_WITHOUT_IDENTITY) {
        throw new Error(
          'Character scene generation did not set identityConditioned=true. Aborting to avoid random-face outputs.'
        );
      }
    }

    workingPath = path.join(tempRoot, `${effectiveSceneId}_attempt_${attempt}.png`);
    await materializeImageSource(lastGeneration.imageSource, workingPath);

    if (!identityPackage) break;

    if (logger) {
      logger(`[IdentityLock] Validating generated face against Character Sheet`);
      logger(`[IdentityLock]   reference: ${identityPackage.referencePath}`);
      logger(`[IdentityLock]   generated: ${workingPath}`);
    }

    const valStartTime = Date.now();
    const validation = await compareWithCharacterMemory(identityPackage, workingPath);
    similarity = validation.similarity;
    const validationDurationMs = Date.now() - valStartTime;
    const totalPipelineTimeMs = (genDurationMs || 0) + validationDurationMs;

    const isPassed = similarity >= config.SIMILARITY_THRESHOLD;
    let failureCategory = null;
    let isRetryable = false;

    if (!isPassed) {
      if (!identityPackage?.referencePath) {
        failureCategory = 'REFERENCE_EMBEDDING_MISSING';
      } else if (validation.engine === 'none' || validation.noFaceDetected) {
        failureCategory = 'NO_FACE_DETECTED';
        isRetryable = true;
      } else {
        failureCategory = 'LOW_SIMILARITY';
        isRetryable = true;
      }
    }

    const telemetryRecord = {
      directorVersion: '2.0',
      sceneBlueprintVersion: '2.0',
      identityPipelineVersion: '2.0',
      comfyWorkflowVersion: '1.4',
      embeddingVersion: identityPackage?.identityToken?.embeddingVersion || 'v2',
      telemetrySchemaVersion: '1.0',
      sceneId: effectiveSceneId,
      characterId: identityPackage.characterId,
      attempt,
      maxRetries: config.MAX_RETRIES,
      seed,
      similarity,
      threshold: config.SIMILARITY_THRESHOLD,
      pulidWeight: config.PULID_WEIGHT || 1.0,
      engine: lastGeneration?.engine || 'comfyui',
      validationEngine: validation.engine,
      generationTimeMs: genDurationMs || 0,
      validationTimeMs: validationDurationMs,
      totalPipelineTimeMs,
      decision: isPassed ? 'ACCEPT' : 'REJECT',
      failureCategory,
      isRetryable,
      createdAt: new Date().toISOString()
    };

    console.log(`[IdentityLock Telemetry]
-----------------------------------------
Scene: ${telemetryRecord.sceneId}
Character: ${telemetryRecord.characterId}
Attempt: #${telemetryRecord.attempt} / ${telemetryRecord.maxRetries}
Seed: ${telemetryRecord.seed}
Similarity Score: ${telemetryRecord.similarity.toFixed(4)} (Threshold: ${telemetryRecord.threshold})
PuLID Weight: ${telemetryRecord.pulidWeight}
Engine: ${telemetryRecord.engine}
Validation Engine: ${telemetryRecord.validationEngine}
Generation Time: ${telemetryRecord.generationTimeMs}ms
Validation Time: ${telemetryRecord.validationTimeMs}ms
Total Pipeline Time: ${telemetryRecord.totalPipelineTimeMs}ms
Decision: ${telemetryRecord.decision}
${telemetryRecord.failureCategory ? `Failure Category: ${telemetryRecord.failureCategory} (Retryable: ${telemetryRecord.isRetryable})` : ''}
-----------------------------------------`);

    if (validation.passes || similarity >= config.SIMILARITY_THRESHOLD) {
      if (logger) {
        logger(`[IdentityLock] ACCEPTED Attempt #${attempt} for ${identityPackage.characterId} (Score ${similarity.toFixed(4)}, engine=${validation.engine})`);
      }
      break;
    }

    if (logger) {
      logger(`[IdentityLock] REJECTED Attempt #${attempt} (${similarity.toFixed(4)} < ${config.SIMILARITY_THRESHOLD}, Category: ${failureCategory}), retrying next attempt...`);
    }
  }

  // ── STEP 5: Face swap is LAST RESORT only (not primary identity creation) ──
  if (
    identityPackage
    && similarity < config.SIMILARITY_THRESHOLD
    && config.ENABLE_FACE_SWAP_FALLBACK
    && workingPath
  ) {
    const swappedPath = path.join(tempRoot, `${effectiveSceneId}_faceswap_last_resort.png`);
    try {
      if (logger) {
        logger('[IdentityLock] LAST RESORT: applying face replacement after identity-conditioned generation failed validation');
      }
      const swapResult = await insightFace.applyFaceSwap({
        referenceImagePath: identityPackage.referencePath,
        targetImagePath: workingPath,
        outputPath: swappedPath
      });
      if (swapResult.success) {
        workingPath = swappedPath;
        faceSwapApplied = true;
        const revalidation = await compareWithCharacterMemory(identityPackage, workingPath);
        similarity = revalidation.similarity;
      }
    } catch (error) {
      if (logger) logger(`[IdentityLock] Face swap last resort unavailable: ${error.message}`);
    }
  }

  // ── STEP 6: Enhance (quality only, identity already set) ──
  const enhancedPath = path.join(tempRoot, `${effectiveSceneId}_final.png`);
  const enhancement = await enhanceImage(workingPath, enhancedPath, { logger });
  if (enhancement.success) {
    workingPath = enhancement.outputPath;
    enhanced = !enhancement.skipped;
  }

  // ── STEP 7: Save ──
  if (localOutputPath) {
    await fs.promises.mkdir(path.dirname(localOutputPath), { recursive: true });
    await fs.promises.copyFile(workingPath, localOutputPath);
  }

  return {
    imageSource: lastGeneration?.imageSource || null,
    localPath: localOutputPath || workingPath,
    similarity,
    attempts,
    faceSwapApplied,
    enhanced,
    identityConditioned,
    generationEngine: lastGeneration?.engine || null,
    geminiUsed: Boolean(lastGeneration?.geminiUsed),
    proof: lastGeneration?.proof || null,
    identityValidated: !identityPackage || similarity >= config.SIMILARITY_THRESHOLD,
    characterMemoryId: identityPackage?.characterId || null,
    characterId: identityPackage?.characterId || null,
    identityMemoryId: identityPackage?.identityMemoryId || identityPackage?.characterId || null,
    referenceImageType: identityPackage?.identityToken?.referenceImageType || 'front_portrait',
    embeddingVersion: identityPackage?.identityToken?.embeddingVersion || 'v2',
    identityModel: identityPackage?.identityToken?.identityModel || 'InsightFace',
    identityMode: identityPackage
      ? (lastGeneration?.geminiUsed ? 'fallback' : 'comfyui')
      : 'none',
    sceneMetadata: {
      sceneNumber: scene.sceneNumber || scene.number || 1,
      sceneTitle: scene.title || 'Scene',
      businessObjective: scene.businessObjective || scene.description || 'Showcase company capabilities',
      marketingMessage: scene.marketingMessage || scene.characterAction || 'High-impact commercial moment',
      primaryCharacter: identityPackage?.characterId || 'Primary',
      location: scene.location || scene.environment || 'Studio set',
      cameraStyle: scene.cameraStyle || scene.camera || '85mm cinema lens',
      referenceImageType: identityPackage?.identityToken?.referenceImageType || 'front_portrait',
      embeddingVersion: identityPackage?.identityToken?.embeddingVersion || 'v2',
      identityModel: identityPackage?.identityToken?.identityModel || 'InsightFace',
      identityMode: identityPackage
        ? (lastGeneration?.geminiUsed ? 'fallback' : 'comfyui')
        : 'none',
      identityConditioned
    },
    warning: identityPackage && lastGeneration?.geminiUsed
      ? 'Generated via Cloud Fallback without ComfyUI identity preservation.'
      : null
  };
}

module.exports = {
  generateSceneImageWithIdentityLock,
  resolveCharacterMemoryForScene
};
