const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const config = require('./identityLockConfig');
const { generateIdentityConditionedSceneImage } = require('./identityConditionedGenerator');
const { enhanceImage } = require('./imageEnhancement');
const insightFace = require('./identityInsightFace');
const {
  resolveCharacterMemoryForScene,
  compareWithCharacterMemory,
  materializeImageSource,
  prepareIdentityPackage
} = require('./characterMemoryStore');

async function generateSceneImageWithIdentityLock({
  scene,
  prompt,
  characterMemory = null,
  draft = null,
  jobId = null,
  sceneId = null,
  localOutputPath = null,
  plan = null,
  identityInstruction = '',
  rawPrompt = false,
  logger = null,
  brandContext = {}
}) {
  const effectiveSceneId = sceneId || scene?.sceneId || 'scene';
  const tempRoot = path.resolve(__dirname, '..', 'storage', 'ai-videos', String(jobId || 'temp'), 'identity-temp');
  await fs.promises.mkdir(tempRoot, { recursive: true });

  // ── STEP 1: Resolve Character Sheet and extract identity BEFORE generation ──
  let resolvedMemory = characterMemory;
  if (!resolvedMemory && draft) {
    resolvedMemory = await resolveCharacterMemoryForScene({ draft, scene, jobId });
  }

  const identityPackage = resolvedMemory
    ? await prepareIdentityPackage(resolvedMemory, logger)
    : null;

  if (identityPackage && logger) {
    logger(`[IdentityLock] Identity prepared for ${identityPackage.characterId} via ${identityPackage.identityEngine}`);
    logger(`[IdentityLock] Character Sheet: ${identityPackage.referencePath}`);
    logger(`[IdentityLock] Identity token: ${identityPackage.tokenPath}`);
  }

  let workingPath = null;
  let lastGeneration = null;
  let similarity = identityPackage ? 0 : 1;
  let attempts = 0;
  let faceSwapApplied = false;
  let enhanced = false;
  let identityConditioned = false;

  // ── STEP 2–4: Identity-conditioned generation → validate (confirm only) ──
  for (let attempt = 1; attempt <= config.MAX_RETRIES; attempt += 1) {
    attempts = attempt;
    const seed = crypto.randomInt(1, 2147483647);

    if (logger) {
      logger(`[IdentityLock] Scene ${effectiveSceneId} identity-conditioned attempt ${attempt}/${config.MAX_RETRIES}`);
    }

    lastGeneration = await generateIdentityConditionedSceneImage({
      prompt,
      scene,
      identityPackage,
      plan,
      identityInstruction,
      rawPrompt,
      seed,
      logger,
      brandContext
    });

    identityConditioned = Boolean(lastGeneration.identityConditioned);

    if (logger && identityPackage) {
      logger(`[IdentityLock] Generation engine: ${lastGeneration.engine} | geminiUsed=${Boolean(lastGeneration.geminiUsed)} | identityConditioned=${identityConditioned}`);
    }

    if (identityPackage && lastGeneration.geminiUsed) {
      throw new Error(
        'Character scene was generated by Gemini instead of ComfyUI. Identity conditioning did not run.'
      );
    }
    if (identityPackage && !lastGeneration.identityConditioned) {
      throw new Error(
        'Character scene generation did not set identityConditioned=true. Aborting to avoid random-face outputs.'
      );
    }

    workingPath = path.join(tempRoot, `${effectiveSceneId}_attempt_${attempt}.png`);
    await materializeImageSource(lastGeneration.imageSource, workingPath);

    if (!identityPackage) break;

    if (logger) {
      logger(`[IdentityLock] Validating generated face against Character Sheet`);
      logger(`[IdentityLock]   reference: ${identityPackage.referencePath}`);
      logger(`[IdentityLock]   generated: ${workingPath}`);
    }

    const validation = await compareWithCharacterMemory(identityPackage, workingPath);
    similarity = validation.similarity;

    if (validation.passes || similarity >= config.SIMILARITY_THRESHOLD) {
      if (logger) {
        logger(`[IdentityLock] Validation confirmed identity (similarity ${similarity.toFixed(3)}, engine=${validation.engine})`);
      }
      break;
    }

    if (logger) {
      logger(`[IdentityLock] Validation below threshold (${similarity.toFixed(3)}), retrying with same identity token`);
    }
  }

  // ── STEP 5: Face swap is LAST RESORT only (not primary identity creation) ──
  if (
    identityPackage
    && similarity < config.SIMILARITY_THRESHOLD
    && config.ENABLE_FACE_SWAP_FALLBACK
    && workingPath
  ) {
    const swappedPath = path.join(tempRoot, `${effectiveSceneId}_faceswap_last_resort.png`);
    try {
      if (logger) {
        logger('[IdentityLock] LAST RESORT: applying face replacement after identity-conditioned generation failed validation');
      }
      const swapResult = await insightFace.applyFaceSwap({
        referenceImagePath: identityPackage.referencePath,
        targetImagePath: workingPath,
        outputPath: swappedPath
      });
      if (swapResult.success) {
        workingPath = swappedPath;
        faceSwapApplied = true;
        const revalidation = await compareWithCharacterMemory(identityPackage, workingPath);
        similarity = revalidation.similarity;
      }
    } catch (error) {
      if (logger) logger(`[IdentityLock] Face swap last resort unavailable: ${error.message}`);
    }
  }

  // ── STEP 6: Enhance (quality only, identity already set) ──
  const enhancedPath = path.join(tempRoot, `${effectiveSceneId}_final.png`);
  const enhancement = await enhanceImage(workingPath, enhancedPath, { logger });
  if (enhancement.success) {
    workingPath = enhancement.outputPath;
    enhanced = !enhancement.skipped;
  }

  // ── STEP 7: Save ──
  if (localOutputPath) {
    await fs.promises.mkdir(path.dirname(localOutputPath), { recursive: true });
    await fs.promises.copyFile(workingPath, localOutputPath);
  }

  return {
    imageSource: lastGeneration?.imageSource || null,
    localPath: localOutputPath || workingPath,
    similarity,
    attempts,
    faceSwapApplied,
    enhanced,
    identityConditioned,
    generationEngine: lastGeneration?.engine || null,
    geminiUsed: Boolean(lastGeneration?.geminiUsed),
    proof: lastGeneration?.proof || null,
    identityValidated: !identityPackage || similarity >= config.SIMILARITY_THRESHOLD,
    characterMemoryId: identityPackage?.characterId || null
  };
}

module.exports = {
  generateSceneImageWithIdentityLock,
  resolveCharacterMemoryForScene
};
