sonar.projectKey=nebulaa
sonar.projectName=Nebulaa

sonar.sources=frontend,backend

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.login=sqp_94cb7737f28f51efd1f1ae5c9a5beecbcc95bf72

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,backend/public/assets/**,backend/storage/**,.claude/**

sonar.javascript.node.maxspace=4096