// Every customer-facing line of the Blueprint landing section, form and progress page.
// The landing text is Option A of the copy document (docs/superpowers/specs/assets/
// brand-growth-blueprint-copy-options.md). Components hold no strings of their own.
// Voice rules: plain complete sentences, no exclamation marks, no emoji, no invented number.
// The Quark amount shown on the form is read from the server, never typed here.

export const BLUEPRINT_COPY = {
  landing: {
    navLabel: 'Free Blueprint',
    eyebrow: 'Get your Brand Growth Blueprint, free',
    headline: 'A written growth plan for your business, free.',
    subline:
      'Tell Nebulaa about your business. You receive a printable Brand Growth Blueprint with what Nebulaa confirmed about your brand, who to speak to, what to post and what to do first.',
    receiveTitle: 'What you receive',
    receive: [
      'What Nebulaa confirmed about your brand from the pages you point to.',
      'Who to speak to, which themes to post about and a month of post ideas.',
      'A roadmap for the months ahead and the first steps to take this week.',
    ],
    legendTitle: 'Every statement is labelled',
    legend: [
      { label: '[Verified]', meaning: 'Confirmed from your own pages or typed by you.' },
      { label: '[Inference]', meaning: 'A conclusion drawn from what was confirmed.' },
      { label: '[Proposed]', meaning: 'A suggestion for you to decide on.' },
      { label: '[Unverified]', meaning: 'Could not be confirmed, so it is marked as such.' },
    ],
    button: 'Get my free Blueprint',
    note: 'It uses a small number of your 100 free Quarks.',
  },
  form: {
    title: 'Your Brand Growth Blueprint',
    intro:
      'Answer a few questions. Nebulaa reads only the pages you point to and writes a printable plan for your business.',
    businessName: 'Business name',
    website: 'Website',
    websitePlaceholder: 'example.com',
    instagram: 'Instagram page',
    instagramPlaceholder: '@yourbusiness',
    reachHelp: 'Add your website, your Instagram page, or both.',
    whatYouSell: 'What you sell',
    whatYouSellHelp: 'One sentence, for example: Custom cakes baked to order.',
    whoItsFor: 'Who it is for',
    whoItsForHelp: 'For example: Families in Chennai.',
    goal: 'Main goal',
    moreDetail: 'Add more detail (optional)',
    city: 'City',
    competitors: 'Competitors, up to three',
    competitorsHelp: 'Nebulaa reads a competitor only when you give an address, and only if the site allows it.',
    addCompetitor: 'Add another competitor',
    competitorName: 'Competitor name',
    competitorUrl: 'Competitor website',
    offers: 'Your offers, up to three',
    offersHelp: 'Enter only real offers with the prices you charge. Nebulaa never adds prices of its own.',
    addOffer: 'Add another offer',
    offerName: 'Offer name',
    offerPrice: 'Price, as you charge it',
    colours: 'Brand colours, up to three',
    addColour: 'Add a colour',
    removeColour: 'Remove this colour',
    logo: 'Logo',
    logoButton: 'Choose a logo',
    logoHelp: 'PNG, JPG or WebP, up to 2 MB. Nebulaa uses your logo exactly as it is.',
    removeLogo: 'Remove the logo',
    modeTitle: 'How should Nebulaa work?',
    modeGuided: 'Guided: you approve what Nebulaa found and choose the direction.',
    modeAuto: 'Automatic: Nebulaa builds the whole plan without stopping.',
    submit: 'Create my Blueprint',
    submitting: 'Starting your Blueprint',
    privacy: 'Nebulaa reads only the pages you point to, and nothing from your answers is published anywhere.',
    openExisting: 'Open your Blueprint',
    correctFields: 'Please correct the highlighted fields.',
  },
  view: {
    stepsLabel: 'Progress',
    confirmedTitle: 'What Nebulaa confirmed',
    unconfirmedTitle: 'What Nebulaa could not confirm',
    missingTitle: 'Not provided',
    nothingConfirmed: 'Nothing could be confirmed from the pages given.',
    limitedBasis: 'Based on limited information',
    continuePlan: 'Continue to the plan',
    continuing: 'Continuing',
    directionsTitle: 'Choose one direction',
    directionRisk: 'Risk',
    useDirection: 'Use this direction',
    changeAnswers: 'Change your answers',
    loadError: 'We could not load your Blueprint. Please refresh the page.',
    continueError: 'We could not continue just now. Please try again.',
    readyTitle: 'Your Blueprint is ready.',
    readyBody: 'Your plan has been written and saved to your account.',
    listTitle: 'Your Blueprints',
    listEmpty: 'You have not created a Blueprint yet. Create one to see a 90-day plan for your business.',
    listNew: 'Create a Blueprint',
    listOpen: 'Open',
    statusLabels: {
      queued: 'In the queue',
      processing: 'Being prepared',
      awaiting_approval: 'Waiting for you',
      completed: 'Ready',
      stopped: 'Stopped',
      failed: 'Not completed',
    },
  },
  document: {
    toolbarLabel: 'Blueprint actions',
    print: 'Print or save as PDF',
    useInCalendar: 'Use this plan in my calendar',
    usingInCalendar: 'Building your calendar',
    calendarNote: 'This builds a new calendar for the current month from the pillars, territory and goal in this plan.',
    calendarError: 'We could not build your calendar just now. Please try again.',
    another: 'Create another Blueprint',
    freeUsed: 'Your free Blueprint is used. Choose a plan to create another.',
    viewPlans: 'View plans and Quarks',
    pageLabel: 'Page',
    coverLabel: 'Brand Growth Blueprint',
    confirmedHeading: 'What we confirmed',
    unconfirmedHeading: 'What we could not confirm',
    nothingListed: 'Nothing is listed here.',
    typedNote: 'Typed by you, shown as entered.',
    preparedOn: 'Prepared on',
    logoNotProvided: 'Logo not provided',
    legendTitle: 'How to read this document',
    legendIntro: 'Every statement carries one of four labels.',
    sourcesTitle: 'Pages read',
    sourcesNone: 'No page could be read.',
    factsRestOn: 'Rests on',
    factIdsLabel: 'Facts',
    territoryLabel: 'Territory',
    audienceLabel: 'Who you speak to',
    competitorSource: 'Their page',
    pillarWhy: 'Why',
    pillarExample: 'Example',
    openDay: 'Open day',
    dayLabel: 'Day',
    offerLabel: 'Offer',
    hookLabel: 'Hook',
    ctaLabel: 'Call to action',
    priorityLabel: 'Priority',
    focusLabel: 'Focus',
    actionsLabel: 'Actions',
    measureLabel: 'What to measure',
    contact: {
      email: 'Email',
      website: 'Website',
      phone: 'Phone',
      instagram: 'Instagram',
      facebook: 'Facebook',
    },
  },
  routes: {
    toDashboard: 'Go to your dashboard',
  },
};
